import { readFileSync } from "fs";
import { join } from "path";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface App {
  name: string;
  slug: string;
  description: string;
  url: string;
  tags: string[];
}

function getApps(): App[] {
  const filePath = join(process.cwd(), "..", "apps.json");
  const data = readFileSync(filePath, "utf-8");
  return JSON.parse(data);
}

export default function Home() {
  const APPS = getApps();
  return (
    <main className="flex-1 flex flex-col items-center p-6 pt-16">
      <div className="w-full max-w-3xl space-y-10">
        <div className="text-center space-y-3">
          <h1 className="text-4xl font-bold tracking-tight">
            <span className="font-mono text-primary">$</span> launchpad
          </h1>
          <p className="text-muted-foreground max-w-lg mx-auto">
            Full-stack web apps built from a single prompt.
            Each app below was generated by AI following a shared{" "}
            <a
              href="https://github.com/azoni/launchpad/blob/main/CLAUDE.md"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              quality checklist
            </a>
            .
          </p>
        </div>

        <div className="grid gap-4">
          {APPS.map((app) => (
            <a
              key={app.slug}
              href={app.url}
              target="_blank"
              rel="noopener noreferrer"
              className="block group"
            >
              <Card className="border-border/50 bg-card/50 backdrop-blur transition-colors hover:border-primary/40">
                <CardContent className="pt-5 pb-5 px-5">
                  <div className="flex items-start justify-between gap-4">
                    <div className="space-y-2 min-w-0">
                      <div className="flex items-center gap-2">
                        <h2 className="text-lg font-semibold group-hover:text-primary transition-colors">
                          {app.name}
                        </h2>
                        <Badge variant="secondary" className="text-xs">
                          live
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {app.description}
                      </p>
                      <div className="flex flex-wrap gap-1.5 pt-1">
                        {app.tags.map((tag) => (
                          <span
                            key={tag}
                            className="text-xs font-mono text-muted-foreground/70 bg-muted/50 px-1.5 py-0.5 rounded"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                    <span className="text-muted-foreground group-hover:text-primary transition-colors shrink-0 mt-1">
                      &rarr;
                    </span>
                  </div>
                </CardContent>
              </Card>
            </a>
          ))}
        </div>

        <div className="text-center space-y-2 pt-4">
          <p className="text-xs text-muted-foreground">
            Powered by{" "}
            <a
              href="https://github.com/azoni/launchpad"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              azoni/launchpad
            </a>
            {" "}&middot;{" "}
            Built by{" "}
            <a
              href="https://azoni.ai"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              azoni.ai
            </a>
          </p>
        </div>
      </div>
    </main>
  );
}
