import type { Metadata } from "next";
import { readFileSync } from "fs";
import { join } from "path";
import Link from "next/link";
import Image from "next/image";
import { ExternalLink, Rocket } from "lucide-react";

interface App {
  name: string;
  slug: string;
  description: string;
  url: string;
  tags: string[];
}

interface CostBySource {
  [source: string]: { events: number; cost: string; tokens: number };
}

function getApps(): App[] {
  const filePath = join(process.cwd(), "..", "apps.json");
  const data = readFileSync(filePath, "utf-8");
  return JSON.parse(data);
}

async function getCosts(): Promise<CostBySource> {
  try {
    const res = await fetch(
      "https://azoni-mcp.onrender.com/activity/cost-summary?days=30",
      {
        headers: {
          Authorization: `Bearer ${process.env.MCP_ADMIN_KEY || process.env.NEXT_PUBLIC_MCP_READ_KEY}`,
        },
        next: { revalidate: 300 }, // refresh every 5 minutes
      }
    );
    if (!res.ok) return {};
    const data = await res.json();
    return data.bySource || {};
  } catch {
    return {};
  }
}

export const metadata: Metadata = {
  title: "Launchpad — AI-Built Web Apps",
  description:
    "A portfolio of full-stack web apps, each built and deployed from a single prompt using Claude Code and a shared quality checklist.",
  openGraph: {
    title: "Launchpad — AI-Built Web Apps",
    description:
      "Full-stack web apps built from a single prompt. Browse the gallery.",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Launchpad — Describe an app. Get a deployed URL.",
      },
    ],
  },
  twitter: { card: "summary_large_image" },
  alternates: {
    canonical: "https://launchpad-console.netlify.app",
  },
};

export default async function Home() {
  const APPS = getApps();
  const costs = await getCosts();

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Launchpad",
    url: "https://launchpad-console.netlify.app",
    description:
      "Full-stack web apps built from a single prompt using Claude Code.",
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <main className="flex-1 flex flex-col items-center p-6 pt-20 bg-grid">
        <div className="w-full max-w-3xl space-y-12">
          {/* Header */}
          <div className="text-center space-y-4">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-neon-muted border border-neon/20 text-neon text-xs font-mono">
              <Rocket className="w-3 h-3" />
              one prompt &rarr; one deployed app
            </div>
            <h1 className="text-5xl font-bold tracking-tight">
              <span className="text-gradient">launchpad</span>
            </h1>
            <p className="text-muted-foreground max-w-lg mx-auto leading-relaxed">
              Full-stack web apps built from a single prompt.
              Each app below was generated by AI following a shared{" "}
              <a
                href="https://github.com/azoni/launchpad/blob/main/CLAUDE.md"
                target="_blank"
                rel="noopener noreferrer"
                className="text-neon hover:underline"
              >
                quality checklist
              </a>
              .
            </p>
          </div>

          {/* App Gallery */}
          <div className="grid gap-3">
            {APPS.map((app) => {
              const source = `launchpad:${app.slug}`;
              const appCost = costs[source];
              const costStr = appCost?.cost; // e.g. "$0.001234"
              const calls = appCost?.events || 0;

              return (
              <a
                key={app.slug}
                href={app.url}
                target="_blank"
                rel="noopener noreferrer"
                className="block group"
              >
                <div className="card-glow card-app p-5">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-start gap-4 min-w-0">
                      <Image
                        src={`${app.url}/icon.svg`}
                        alt={`${app.name} icon`}
                        width={36}
                        height={36}
                        className="rounded-lg shrink-0 mt-0.5"
                      />
                      <div className="space-y-2 min-w-0">
                        <div className="flex items-center gap-2.5">
                          <h2 className="text-lg font-semibold group-hover:text-neon transition-colors">
                            {app.name}
                          </h2>
                          <span className="badge-live">live</span>
                          {costStr && (
                            <span className="badge-cost" title={`${calls} LLM calls (30d)`}>
                              {costStr}
                            </span>
                          )}
                        </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {app.description}
                      </p>
                      <div className="flex flex-wrap gap-1.5 pt-1">
                        {app.tags.map((tag) => (
                          <span
                            key={tag}
                            className="text-xs font-mono text-muted-foreground/60 bg-secondary px-2 py-0.5 rounded"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                      </div>
                    </div>
                    <ExternalLink className="w-4 h-4 text-muted-foreground/40 group-hover:text-neon transition-colors shrink-0 mt-1.5" />
                  </div>
                </div>
              </a>
              );
            })}
          </div>

          {/* Build CTA */}
          <div className="text-center">
            <Link href="/console" className="btn-neon">
              Build Your Own
              <Rocket className="w-4 h-4" />
            </Link>
          </div>

          {/* Footer */}
          <footer className="text-center space-y-2 pt-4 pb-8">
            <p className="text-xs text-muted-foreground/50">
              Powered by{" "}
              <a
                href="https://github.com/azoni/launchpad"
                target="_blank"
                rel="noopener noreferrer"
                className="text-muted-foreground/70 hover:text-neon transition-colors"
              >
                azoni/launchpad
              </a>
              {" "}&middot;{" "}
              Built by{" "}
              <a
                href="https://azoni.ai"
                target="_blank"
                rel="noopener noreferrer"
                className="text-muted-foreground/70 hover:text-neon transition-colors"
              >
                azoni.ai
              </a>
            </p>
          </footer>
        </div>
      </main>
    </>
  );
}
